# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import EmployeeService_pb2 as EmployeeService__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in EmployeeService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmployeeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEmployee = channel.unary_unary(
                '/employee_service.EmployeeService/CreateEmployee',
                request_serializer=EmployeeService__pb2.EmployeeData.SerializeToString,
                response_deserializer=EmployeeService__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetEmployeeDataFromID = channel.unary_unary(
                '/employee_service.EmployeeService/GetEmployeeDataFromID',
                request_serializer=EmployeeService__pb2.EmployeeID.SerializeToString,
                response_deserializer=EmployeeService__pb2.EmployeeData.FromString,
                _registered_method=True)
        self.UpdateEmployeeTitle = channel.unary_unary(
                '/employee_service.EmployeeService/UpdateEmployeeTitle',
                request_serializer=EmployeeService__pb2.EmployeeTitleUpdate.SerializeToString,
                response_deserializer=EmployeeService__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DeleteEmployee = channel.unary_unary(
                '/employee_service.EmployeeService/DeleteEmployee',
                request_serializer=EmployeeService__pb2.EmployeeID.SerializeToString,
                response_deserializer=EmployeeService__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ListAllEmployees = channel.unary_unary(
                '/employee_service.EmployeeService/ListAllEmployees',
                request_serializer=EmployeeService__pb2.EmptyMessage.SerializeToString,
                response_deserializer=EmployeeService__pb2.EmployeeDataList.FromString,
                _registered_method=True)
        self.GetEmployeesByTitle = channel.unary_unary(
                '/employee_service.EmployeeService/GetEmployeesByTitle',
                request_serializer=EmployeeService__pb2.EmployeeTitle.SerializeToString,
                response_deserializer=EmployeeService__pb2.EmployeeDataList.FromString,
                _registered_method=True)
        self.CountEmployees = channel.unary_unary(
                '/employee_service.EmployeeService/CountEmployees',
                request_serializer=EmployeeService__pb2.EmptyMessage.SerializeToString,
                response_deserializer=EmployeeService__pb2.EmployeeCount.FromString,
                _registered_method=True)


class EmployeeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEmployee(self, request, context):
        """Create an employee record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeeDataFromID(self, request, context):
        """Get an employee´s data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmployeeTitle(self, request, context):
        """Update an employee´s title/position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmployee(self, request, context):
        """Delete an employee
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllEmployees(self, request, context):
        """List all employees
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeesByTitle(self, request, context):
        """Get employees by title
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountEmployees(self, request, context):
        """Count total employees
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmployeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmployee,
                    request_deserializer=EmployeeService__pb2.EmployeeData.FromString,
                    response_serializer=EmployeeService__pb2.StatusReply.SerializeToString,
            ),
            'GetEmployeeDataFromID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeeDataFromID,
                    request_deserializer=EmployeeService__pb2.EmployeeID.FromString,
                    response_serializer=EmployeeService__pb2.EmployeeData.SerializeToString,
            ),
            'UpdateEmployeeTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmployeeTitle,
                    request_deserializer=EmployeeService__pb2.EmployeeTitleUpdate.FromString,
                    response_serializer=EmployeeService__pb2.StatusReply.SerializeToString,
            ),
            'DeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmployee,
                    request_deserializer=EmployeeService__pb2.EmployeeID.FromString,
                    response_serializer=EmployeeService__pb2.StatusReply.SerializeToString,
            ),
            'ListAllEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllEmployees,
                    request_deserializer=EmployeeService__pb2.EmptyMessage.FromString,
                    response_serializer=EmployeeService__pb2.EmployeeDataList.SerializeToString,
            ),
            'GetEmployeesByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeesByTitle,
                    request_deserializer=EmployeeService__pb2.EmployeeTitle.FromString,
                    response_serializer=EmployeeService__pb2.EmployeeDataList.SerializeToString,
            ),
            'CountEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.CountEmployees,
                    request_deserializer=EmployeeService__pb2.EmptyMessage.FromString,
                    response_serializer=EmployeeService__pb2.EmployeeCount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'employee_service.EmployeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('employee_service.EmployeeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmployeeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/CreateEmployee',
            EmployeeService__pb2.EmployeeData.SerializeToString,
            EmployeeService__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeeDataFromID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/GetEmployeeDataFromID',
            EmployeeService__pb2.EmployeeID.SerializeToString,
            EmployeeService__pb2.EmployeeData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmployeeTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/UpdateEmployeeTitle',
            EmployeeService__pb2.EmployeeTitleUpdate.SerializeToString,
            EmployeeService__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/DeleteEmployee',
            EmployeeService__pb2.EmployeeID.SerializeToString,
            EmployeeService__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/ListAllEmployees',
            EmployeeService__pb2.EmptyMessage.SerializeToString,
            EmployeeService__pb2.EmployeeDataList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeesByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/GetEmployeesByTitle',
            EmployeeService__pb2.EmployeeTitle.SerializeToString,
            EmployeeService__pb2.EmployeeDataList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee_service.EmployeeService/CountEmployees',
            EmployeeService__pb2.EmptyMessage.SerializeToString,
            EmployeeService__pb2.EmployeeCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
