# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EmployeeService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EmployeeService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45mployeeService.proto\x12\x10\x65mployee_service\"7\n\x0c\x45mployeeData\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x18\n\nEmployeeID\x12\n\n\x02id\x18\x01 \x01(\r\"0\n\x13\x45mployeeTitleUpdate\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\"\x1e\n\rEmployeeTitle\x12\r\n\x05title\x18\x01 \x01(\t\"\x1e\n\rEmployeeCount\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"\x0e\n\x0c\x45mptyMessage\"I\n\x10\x45mployeeDataList\x12\x35\n\remployee_data\x18\x01 \x03(\x0b\x32\x1e.employee_service.EmployeeData2\xfa\x04\n\x0f\x45mployeeService\x12Q\n\x0e\x43reateEmployee\x12\x1e.employee_service.EmployeeData\x1a\x1d.employee_service.StatusReply\"\x00\x12W\n\x15GetEmployeeDataFromID\x12\x1c.employee_service.EmployeeID\x1a\x1e.employee_service.EmployeeData\"\x00\x12]\n\x13UpdateEmployeeTitle\x12%.employee_service.EmployeeTitleUpdate\x1a\x1d.employee_service.StatusReply\"\x00\x12O\n\x0e\x44\x65leteEmployee\x12\x1c.employee_service.EmployeeID\x1a\x1d.employee_service.StatusReply\"\x00\x12X\n\x10ListAllEmployees\x12\x1e.employee_service.EmptyMessage\x1a\".employee_service.EmployeeDataList\"\x00\x12\\\n\x13GetEmployeesByTitle\x12\x1f.employee_service.EmployeeTitle\x1a\".employee_service.EmployeeDataList\"\x00\x12S\n\x0e\x43ountEmployees\x12\x1e.employee_service.EmptyMessage\x1a\x1f.employee_service.EmployeeCount\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EmployeeService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _globals['_EMPLOYEEDATA']._serialized_start=43
  _globals['_EMPLOYEEDATA']._serialized_end=98
  _globals['_STATUSREPLY']._serialized_start=100
  _globals['_STATUSREPLY']._serialized_end=129
  _globals['_EMPLOYEEID']._serialized_start=131
  _globals['_EMPLOYEEID']._serialized_end=155
  _globals['_EMPLOYEETITLEUPDATE']._serialized_start=157
  _globals['_EMPLOYEETITLEUPDATE']._serialized_end=205
  _globals['_EMPLOYEETITLE']._serialized_start=207
  _globals['_EMPLOYEETITLE']._serialized_end=237
  _globals['_EMPLOYEECOUNT']._serialized_start=239
  _globals['_EMPLOYEECOUNT']._serialized_end=269
  _globals['_EMPTYMESSAGE']._serialized_start=271
  _globals['_EMPTYMESSAGE']._serialized_end=285
  _globals['_EMPLOYEEDATALIST']._serialized_start=287
  _globals['_EMPLOYEEDATALIST']._serialized_end=360
  _globals['_EMPLOYEESERVICE']._serialized_start=363
  _globals['_EMPLOYEESERVICE']._serialized_end=997
# @@protoc_insertion_point(module_scope)
